module:
    hugoVersion:
        extended: true
        min: "0.87.0"

params:
    mainSections:
        - post
    featuredImageField: image
    rssFullContent: true
    favicon: /tianyi.ico

    footer:
        since:
        customText:

    dateFormat:
        published: Jan 02, 2006
        lastUpdated: Jan 02, 2006 15:04 MST

    sidebar:
        compact: false
        emoji: 
        subtitle: 至少在这一刻，热爱不问为何！
        avatar:
            enabled: true
            local: false
            src: /avatar.webp

    article:
        headingAnchor: false
        math: false
        toc: true
        readingTime: true
        license:
            enabled: true
            default: Licensed under CC BY-NC-SA 4.0

    comments:
        enabled: false
        provider: disqus

        disqusjs:
            shortname:
            apiUrl:
            apiKey:
            admin:
            adminLabel:

        utterances:
            repo:
            issueTerm: pathname
            label:

        beaudar:
            repo:
            issueTerm: pathname
            label:
            theme:        

        remark42:
            host:
            site:
            locale:

        vssue:
            platform:
            owner:
            repo:
            clientId:
            clientSecret:
            autoCreateIssue: false

        # Waline client configuration see: https://waline.js.org/en/reference/client/props.html
        waline:
            serverURL:
            lang:
            visitor:
            avatar:
            emoji:
                - https://cdn.jsdelivr.net/gh/walinejs/emojis/weibo
            requiredMeta:
                - nick
                - mail
            locale:
                admin: Admin
                placeholder:

        twikoo:
            envId:
            region:
            path:
            lang:

        giscus:
            repo:
            repoID:
            category:
            categoryID:
            mapping:
            strict:
            lightTheme:
            darkTheme:
            reactionsEnabled: 1
            emitMetadata: 0
            inputPosition:
            lang:

        gitalk:
            owner:
            admin:
            repo:
            clientID:
            clientSecret:

        cusdis:
            host:
            id:

    widgets:
        homepage:
            - type: search
            - type: archives
              params:
                  limit: 5
            - type: categories
              params:
                  limit: 10
            - type: tag-cloud
              params:
                  limit: 10
        page:
            - type: toc

    opengraph:
        twitter:
            # Your Twitter username
            site:

            # Available values: summary, summary_large_image
            card: summary_large_image

    defaultImage:
        opengraph:
            enabled: false
            local: false
            src:

    colorScheme:
        # Display toggle
        toggle: true

        # Available values: auto, light, dark
        default: auto

    imageProcessing:
        cover:
            enabled: false
        content:
            enabled: false

menu:
    main:
        - identifier: home
          name: Home
          url: /
          weight: -100
          params:
            icon: home
            newtab: false
    social:
        - identifier: github
          name: GitHub
          url: https://github.com/ClF3
          params:
              icon: brand-github
        - identifier: bilibili
          name: Bilibili
          url: https://space.bilibili.com/432957407
          params:
              icon: brand-bilibili
        - identifier: run
          name: Running Page
          url: https://run.clf3.org
          params:
              icon: run
        - identifier: mail
          name: Mail
          url: mailto:clf3@clf3.org
          params:
              icon: mail
        - identifier: status
          name: Status
          url: https://status.clf3.org
          params:
              icon: align-box-bottom-center
              newtab: true